### ISSUE TITLE
default status bar unthemed

### ISSUE THREAD

**Issue by Miosame** [codesbiome/soil-theme-vscode#1]
First of all thanks so much for this theme! been trying to find one like this for a long while, especially one that is so polished.

However there's the issue that if you open vscode without a workspace, it won't theme the bottom bar
![image](https://user-images.githubusercontent.com/8201077/91675886-42d55b80-eb3e-11ea-844f-ba10b01a1569.png)
(top workspace opened, bottom just single file instance)

**Comment by codesbiome** [comment]
Thanks for providing the feedback. 

> been trying to find one like this for a long while, especially one that is so polished.

Same, been looking for one that fits the need (visually). Sadly there was no option but to get the hands dirty and make one.

<br />

> However there's the issue that if you open vscode without a workspace, it won't theme the bottom bar

Just added the requested fix #2 into a minor version of this Theme. Hopefully it will update the source in `Marketplace` too.
If you find any other 🐛 bug or issue, feel free to submit here.

Cheers!

**Comment by Miosame** [comment]
> Same, been looking for one that fits the need (visually). Sadly there was no option but to get the hands dirty and make one.

There has been a lot that were close, but were failing somewhere else, your theme is the only one that got everything right, deep appreciation and kudos to you.

I wanted to attempt at it myself too plethora of times, but there was just an overwhelming amount of colors to have to set and figure out, that I always had to give up eventually.

**Comment by codesbiome** [comment]
> There has been a lot that were close, but were failing somewhere else, your theme is the only one that got everything right, deep appreciation and kudos to you.

Thank you Miosame, its glad to know you liked it!

Yep, there are plenty of choices nowadays for the Themes, used to run a Dark one in past, but decided to play with colors and see how far it can go. Ended up creating a new color theme instead. 

<br />

> I wanted to attempt at it myself too plethora of times, but there was just an overwhelming amount of colors to have to set and figure out, that I always had to give up eventually.

That's true, the requirement of colors and messing around with theme scopes can take a while. 
It was a long fight here too, because I got really terrible eyes when it comes to the color choices 🙂
