### ISSUE TITLE
Monokai version?

### ISSUE THREAD

**Issue by Miosame** [codesbiome/soil-theme-vscode#3]
Not sure what the licensing there is on monokai, but it's a very popular sub-theme to have and fits this theme extremely well when applied. You can locally build / preview from [this commit](https://github.com/Miosame/soil-theme-vscode/commit/d6d21140e3c47cef3301e3616125ce6f1c665748) and try it for yourself first before I'll PR. 

I took these changes from [styncy implementing monokai](https://github.com/goncy/styncy/blob/master/themes/Styncy-color-theme-monokai.json). Styncy itself has no license published either, so possibly copyright reserved?

I have reviewed how styncy added sub-themes also and went ahead to add it already in previously mentioned commit, just select the monokai version when previewing to see it in action.

You're free to ignore this commit too and I'll just keep it in my fork, in case licensing is too much a hassle or an unknown variable that could get you in trouble somehow with vscode marketplace publishing, or simply because you think monokai doesn't fit the vision of this theme.

Cheers!

**Comment by codesbiome** [comment]
Alrighty, i'll give it a try to see in action in Development mode. 

<br />

> I took these changes from styncy implementing monokai. Styncy itself has no license published either, so possibly copyright reserved?

Ye, it seems like Copyright Reserved. No license attached into repository or README file.

**Comment by Miosame** [comment]
I've filed an [issue with styncy](https://github.com/goncy/styncy/issues/1) asking about the license and origin, that could clear up if it's possible to use it at all.

I'm mostly fearing those might be extracted from a [paid monokai pro theme](https://monokai.pro/vscode) package. Styncy been up for a very long time both in the store and on github though, so I have hopes it's a standalone theme and the creator could shed some light.

**Comment by Miosame** [comment]
@codesbiome it's now [GPLv3 licensed](https://github.com/goncy/styncy/blob/master/LICENSE) - which should be MIT compatible.

Please remember that this is still up to you, don't feel pressured into this - especially if you don't see this fitting the themes vision or having to include a notice for the monokai sub-theme, just wanted to notify of the license change, which now allows other themes to add this as a sub-theme. 😄

**Comment by codesbiome** [comment]
I just gave it a spin in development mode, it looks like the color scheme in editor codes is changed mostly. 
Editor Interface related colors are still the same, is it correct?

![image](https://user-images.githubusercontent.com/46080054/92297523-e028f900-ef5d-11ea-8899-2707946e08da.png)

<br />

> Please remember that this is still up to you, don't feel pressured into this - especially if you don't see this fitting the themes vision or having to include a notice for the monokai sub-theme, just wanted to notify of the license change, which now allows other themes to add this as a sub-theme.

Its okay 🙂 having a sub-theme including with some additional color scheme for codes is a good idea.  

Wondering if the colors used on that [commit](https://github.com/Miosame/soil-theme-vscode/commit/d6d21140e3c47cef3301e3616125ce6f1c665748) would require some tweaks to fit for lower contrast? Or the purpose of this sub-theme would be to have higher contrast (monokai) colors for codes?

**Comment by Miosame** [comment]
@codesbiome Indeed, that sub-theme purely adjusts the syntax theme, everything else outside of that stays the same. :smiley:

For the question, I am using it on a pretty harsh contrast setting on desktop and it still works well, so I would believe it should be fine as is, not too dark neither too bright to not be able to distinguish code, soil by default passes it I'd say.

**Comment by codesbiome** [comment]
> Indeed, that sub-theme purely adjusts the syntax theme, everything else outside of that stays the same. 

That's good 🙂

<br />

> For the question, I am using it on a pretty harsh contrast setting on desktop and it still works well, so I would believe it should be fine as is, not too dark neither too bright to not be able to distinguish code, soil by default passes it I'd say.

Cool, lemme know if you wish to create PR regarding changes for this sub-theme.
I will include them for the next version of Soil Theme, along with the patch for #4

**Comment by codesbiome** [comment]
In this [commit](https://github.com/Miosame/soil-theme-vscode/commit/d6d21140e3c47cef3301e3616125ce6f1c665748), the filename of sub-theme is `soil-color-theme-monokai.json`
When editing this file in VScode, it doesn't display the `color picker` for the values of theme colors : 
> ![image](https://user-images.githubusercontent.com/46080054/92987690-7ae78180-f4e2-11ea-970a-4cbfaa965316.png)

<br />

If the filename could change to something like `soil-monokai-color-theme.json` that'd be nice :
> ![image](https://user-images.githubusercontent.com/46080054/92987790-6b1c6d00-f4e3-11ea-858a-490ac45dc26e.png)

**Comment by Miosame** [comment]
@codesbiome 
I think it's not showing the color picker because of this:

![image](https://user-images.githubusercontent.com/8201077/93003168-c2026080-f53c-11ea-95b1-90ed1b47607a.png)

Oddly enough the same error doesn't show up in your .json though.
Validating your json brings up many errors caused by comments, for example this line:

https://github.com/codesbiome/soil-theme-vscode/blob/c7b27d8bb21dcc76dc8b9b70216b04ae52194337/themes/soil-color-theme.json#L71

gets intepreted as this:

![image](https://user-images.githubusercontent.com/8201077/93003337-1c4ff100-f53e-11ea-9287-d6a1ce529973.png)

You can see the rest that makes it not validate by pasting the current theme .json into here: https://jsonformatter.curiousconcept.com

That all causes vscode to not identify your file as valid json, therefore the comments aren't error'd and the color picker shows up. 
Not sure why mine passes as json though, since in the same validator it also fails, albeit with less errors.

I have renamed the file and made a PR, [here](https://github.com/codesbiome/soil-theme-vscode/pull/5). I have allowed maintainer edits, so we can further fix things if necessary before merging.

**Comment by codesbiome** [comment]
> I think it's not showing the color picker because of this:

Seems like the `color-picker` in vscode requires the **name of theme file** to be specially suffixed with `color-theme.json` to be a valid color theme file.

<br />

> Oddly enough the same error doesn't show up in your .json though.
Validating your json brings up many errors caused by comments, for example this line:

> That all causes vscode to not identify your file as valid json, therefore the comments aren't error'd and the color picker shows up. Not sure why mine passes as json though, since in the same validator it also fails, albeit with less errors.

Ye, comments are not allowed in `.json` files, that's why the validation is showing them as errors. They're only supported in `.jsonc` file extensions.

Using these comments just to have a named-separator between editor properties _(to prevent confusion)_. Also thought about using `.jsonc` as a theme file but then `vscode` itself doesn't allow it to bundle for theme extension. 

<br />

> I have renamed the file and made a PR, here. I have allowed maintainer edits, so we can further fix things if necessary before merging.

Nice, yes there will be some tweaks needs to be done before merging 👍🏻
Cheers!

**Comment by Miosame** [comment]
@codesbiome I assume the theme is fully merged and we can close? cheers! :clinking_glasses: :tada:

**Comment by codesbiome** [comment]
Sure, I will also be working on publishing it with the next minor version of Soil Theme.
Cheers! 🥂
