### ISSUE TITLE
selection "invisible" inside textbox

### ISSUE THREAD

**Issue by Miosame** [codesbiome/soil-theme-vscode#7]
Selecting pieces of text inside textboxes very slightly alters the text, not clearly distinguishing what's selected, maybe it would be good to change it to an orange/brownish color like the selected item in the omnibar? :smile: 

Here is selected text as of now:
![image](https://user-images.githubusercontent.com/8201077/95029366-039faa80-06a8-11eb-9246-36320fd50807.png)

and here's the orange'ish color mentioned:
![image](https://user-images.githubusercontent.com/8201077/95029352-e2d75500-06a7-11eb-8826-77afeed0d9c9.png)

**Comment by codesbiome** [comment]
That's a good idea Miosame, how about this color for the selection of text in textarea?

![image](https://user-images.githubusercontent.com/46080054/95089996-69407500-0742-11eb-9ffb-b5b446d0d40e.png)

**Comment by Miosame** [comment]
@codesbiome yep that's exactly what I was thinking, for theme consistency :smile:

**Comment by codesbiome** [comment]
Thanks miosame, changes are added dd8e8f7836f1190a466b47e68c3c3544f8e2a2b7
Just published the theme extension with all pending changes and fixes, it might take a while to reflect as an update for Visual Studio Code.

If you notice any issues, feel free to advise
Cheers!

**Comment by Miosame** [comment]
Interestingly enough 1.1.0 is already in the store, but the selection color did not yet make it in, is that a problem with vscode market?

**Comment by codesbiome** [comment]
Can you tell which textbox you were mentioning in https://github.com/codesbiome/soil-theme-vscode/issues/7#issue-714423369

I notice , the changes for selection color is not applied to the textbox of `Source Control - Commit Message` text field here: 

![image](https://user-images.githubusercontent.com/46080054/95122478-357b4480-076e-11eb-897f-cc0f3b7e1d57.png)

But they are applied fine for areas like Settings, Find/Replace etc:

![image](https://user-images.githubusercontent.com/46080054/95122762-9a369f00-076e-11eb-973c-da74f7072abf.png)

**Comment by Miosame** [comment]
I'm usually checking these two, the sidebar textboxes (source control, market, search, ..)

![image](https://user-images.githubusercontent.com/8201077/95123946-06a3a500-0753-11eb-9eb0-389cba4479d5.png)

and the omni-bar via ctrl+shift+p or ctrl+p

![image](https://user-images.githubusercontent.com/8201077/95124141-479bb980-0753-11eb-88a0-8cb9e2273612.png)

Both screenshots have the full text selected.

**Comment by codesbiome** [comment]
Applied some changes regarding it in commit c44dfd18256ec1adaa0f6fce6a414ff0d846a657
It applies text selection color for all areas you mentioned (`source control, market, search`)

**Search**: 

![image](https://user-images.githubusercontent.com/46080054/95158931-6bdeb100-07ba-11eb-8f37-500739e72599.png)

**Source Control**: 

![image](https://user-images.githubusercontent.com/46080054/95158971-82850800-07ba-11eb-9c8c-17aa347bd90a.png)

**Extension Market**:

![image](https://user-images.githubusercontent.com/46080054/95158998-93ce1480-07ba-11eb-9690-cff547c6bf9c.png)

**Omni Bar**:

![image](https://user-images.githubusercontent.com/46080054/95159117-df80be00-07ba-11eb-8003-27a2dee04f8f.png)

**Comment by Miosame** [comment]
@codesbiome was that tagged for vscode market already?

**Comment by codesbiome** [comment]
Yes miosame, it is published for vscode marketplace now.

**Comment by Miosame** [comment]
@codesbiome just noticed, the change has also be done to the monokai theme - that's why I wasn't seeing it

**Comment by codesbiome** [comment]
Hello Miosame,
I've just pushed the changes to new minor version 506b4b15ff8f56f25ebd1434ac7f0fb2983b8f5b , along with some other changes.

**Comment by Miosame** [comment]
@codesbiome thanks a lot! :tada: :raised_hands: looks like it's been pushed to the store already and is working! closing this.
