### ISSUE TITLE
"passwords" key gets "as" highlighted

### ISSUE THREAD

**Issue by Miosame** [codesbiome/soil-theme-vscode#8]
That's on this line: https://github.com/laravel/fortify/blob/bfcc01219b0b10dd7b9161aa9da33af28f566320/stubs/fortify.php#L32

![image](https://user-images.githubusercontent.com/8201077/95031353-ccd09100-06b5-11eb-9651-688eaf0dccec.png)

Not sure if that's a bug with the php language server or the theme definition?

**Comment by codesbiome** [comment]
Its a duplicate of #4 

> Not sure if that's a bug with the php language server or the theme definition?

Its related with custom grammar syntax used in the Soil theme.
Upcoming patch will include some fix b979b50944527288a892115f984e4bc83bd7ca2e regarding it.

Cheers!

**Comment by Miosame** [comment]
Closing as duplicate then! Cheers! :tada:
