### ISSUE TITLE
Highlight colors broke with new vscode updates

### ISSUE THREAD

**Issue by Miosame** [codesbiome/soil-theme-vscode#9]
Can't right now figure out myself what they've changed that made the old orange go away and fallback to the default blue, but now after some of the new vsCode updates - menu items are highlighted with default blue:

![image](https://user-images.githubusercontent.com/8201077/110715543-bbac2300-8205-11eb-9c6e-6bef4b448457.png)

**Comment by codesbiome** [comment]
Hello @Miosame, can you try adding in `colors` property of the `themes/xxx-color-theme.json` file: 

```json
"quickInput.list.focusBackground": "#b35118d8"
```

**Comment by Miosame** [comment]
@codesbiome yep that's it! that solves it, both for monokai and regular. :+1:

**Comment by codesbiome** [comment]
@Miosame Just merged the pull request.  
Feel free to advise if there's any other bugfix/patch you wish to include, before we push the new version to the Marketplace.
Cheers!

**Comment by Miosame** [comment]
@codesbiome Yeah I saw, thanks for the quick merge! :tada: I haven't found any other issues yet, if there will be I'll open an issue, cheers!

**Comment by codesbiome** [comment]
Seems like there was a slight update in property name we used to fix this. 

Old property name :
```json
"quickInput.list.focusBackground": "#b35118d8"
```

Now its updated to : 

```json
"quickInputList.focusBackground": "#b35118d8"
```

**Comment by codesbiome** [comment]
> Yeah I saw, thanks for the quick merge! 🎉 I haven't found any other issues yet, if there will be I'll open an issue, cheers!

Your welcome 🎉
Just pushed the new changes of version `v1.1.3` for Marketplace , also included `Monokai Subtheme` screenshot for README file.
